global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api_gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api_gateway:8080']
        labels:
          service: 'api_gateway'

  - job_name: 'data_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['data_service:5001']
        labels:
          service: 'data_service'

  - job_name: 'training_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['training_service:5002']
        labels:
          service: 'training_service'

  - job_name: 'prediction_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['prediction_service:5003']
        labels:
          service: 'prediction_service'
